import 'package:sekka/Core/Localization/app_localizations.dart';



abstract final class AppText {

  AppText._();

  static AppLocalizations get _s => AppLocalizations.effective;
  static String get  pleaseSelectStation=> _s.sameStation;
  static String get skip => _s.skip;
  static String get save=> _s.save;
  static String get editProfile=> _s.editProfile;
  static String get sekkaMember => _s.sekkaMember;
  static String get profile => _s.profile;
  static String get journeyDetails => _s.journeyDetails; 
  static String get selectTransport => _s.selectTransport;
  static String get planYourRoute => _s.planYourRoute;
  static String get bestPathDestination => _s.bestPathDestination;
  static String get startAndEndCantBeTheSame => _s.startAndEndCantBeTheSame;
  static String get selectMetroStart => _s.selectMetroStart;
  static String get selectMetroEnd => _s.selectMetroEnd;  
  static String get appName => _s.appName;
  static String get search => _s.search;
  static String get loading => _s.loading;
  static String get maxAttemptsForVerf => _s.maxAttemptsForVerf;
  static String get resendEmailIn => _s.resendEmailIn;
  static String get iHaveVerifiedMyEmail => _s.iHaveVerifiedMyEmail;
  static String get resendEmailVerification => _s.resendEmailVerification;
  static String get checkYourInBox => _s.checkYourInBox;
  static String get clickYourVerificationLink => _s.clickYourVerificationLink;
  static String get receiveEmail => _s.receiveEmail;
  static String get checkYourSpam => _s.checkYourSpam;
  static String get makeSureYourEmailIsCorrect => _s.makeSureYourEmailIsCorrect;
  static String get waitFewMinutes => _s.waitFewMinutes;
  static String get signInSuccessfully => _s.signInSuccessfully;
  static String get backToLogin => _s.backToLogin;
  static String get createAccount => _s.createAccount;
  static String get joinSekkaAndTravelSmart => _s.joinSekkaAndTravelSmart;
  static String get phone => _s.phone;
  static String get email => _s.email;
  static String get fullName => _s.fullName;
  static String get phoneNumber => _s.phoneNumber;
  static String get emailAddress => _s.emailAddress;
  static String get password => _s.password;
  static String get confirmPassword => _s.confirmPassword;
  static String get enterYourName => _s.enterYourName;
  static String get enterYourEmail => _s.enterYourEmail;
  static String get enterYourPhoneNumber => _s.enterYourPhoneNumber;
  static String get enterYourPassword => _s.enterYourPassword;
  static String get enterYourConfirmPassword => _s.enterYourConfirmPassword;
  static String get passwordMustContain => _s.passwordMustContain;
  static String get validationSpecialCharacter => _s.validationSpecialCharacter;
  static String get validationUpperCase => _s.validationUpperCase;
  static String get validationLowerCase => _s.validationLowerCase;
  static String get validationTextLength => _s.validationTextLength;
  static String get validationNumber => _s.validationNumber;
  static String get validationPhone => _s.validationPhone;
  static String get iAgreeToThe => _s.iAgreeToThe;
  static String get termsOfService => _s.termsOfService;
  static String get and => _s.and;
  static String get privacyPolicy => _s.privacyPolicy;
  static String get alreadyHaveAnAccount => _s.alreadyHaveAnAccount;
  static String get verifiedEmail => _s.verifiedEmail;
  static String get signIn => _s.signIn;
  static String get welcomeToSekka => _s.welcomeToSekka;
  static String get smartTransportation => _s.smartTransportation;
  static String get forgotPassword => _s.forgotPassword;
  static String get dontHaveAnAccount => _s.dontHaveAnAccount;
  static String get signUp => _s.signUp;
  static String get verifyPhoneNumber => _s.verifyPhoneNumber;
  static String get verifyEmail => _s.verifyEmail;
  static String get verifyEmailTitle => _s.verifyEmailTitle;
  static String get sentVerificationEmail => _s.sentVerificationEmail;
  static String get verificationFailed => _s.verificationFailed;
  static String get enterVerificationCode => _s.enterVerificationCode;
  static String get send6DigitCode => _s.send6DigitCode;
  static String get otpInstruction => _s.otpInstruction;
  static String get emailIsEmpty => _s.emailIsEmpty;
  static String get emailIsNotValid => _s.emailIsNotValid;
  static String get passwordIsEmpty => _s.passwordIsEmpty;
  static String get phoneIsEmpty => _s.phoneIsEmpty;
  static String get phoneIsNotValid => _s.phoneIsNotValid;
  static String get passwordIsNotValid => _s.passwordIsNotValid;
  static String get passwordIsTooShort => _s.passwordIsTooShort;
  static String get connectionTimeOut => _s.connectionTimeOut;
  static String get sendTimeOut => _s.sendTimeOut;
  static String get receiveTimeOut => _s.receiveTimeOut;
  static String get badRequest => _s.badRequest;
  static String get unauthorized => _s.unauthorized;
  static String get forbidden => _s.forbidden;
  static String get notFound => _s.notFound;
  static String get internalServerError => _s.internalServerError;
  static String get somethingWentWrong => _s.somethingWentWrong;
  static String get cancel => _s.cancel;
  static String get connectionError => _s.connectionError;
  static String get unExpectedError => _s.unExpectedError;
  static String get passwordRecoveryText => _s.passwordRecoveryText;
  static String get passwordHelpYou => _s.passwordHelpYou;
  static String get backToSignUp => _s.backToSignUp;
  static String get completeYourProfile => _s.completeYourProfile;
  static String get helpUsPersonalizeYourSekkaExperience =>
      _s.helpUsPersonalizeYourSekkaExperience;
  static String get tellUsAboutYourSelf => _s.tellUsAboutYourSelf;
  static String get letsStartWithTheBasics => _s.letsStartWithTheBasics;
  static String get profilePicture => _s.profilePicture;
  static String get yourProfileHelpUsProvide => _s.yourProfileHelpUsProvide;
  static String get personalizedRouteSuggestionsAnd =>
      _s.personalizedRouteSuggestionsAnd;
  static String get notifications => _s.notifications;
  static String get continuee => _s.continuee;
  static String get preferredTransport => _s.preferredTransport;
  static String get selectYourFavModeOfTransportation =>
      _s.selectYourFavModeOfTransportation;
  static String get invalidPhoneNumber => _s.invalidPhoneNumber;
  static String get invalidLogin => _s.invalidLogin;
  static String get userNotFound => _s.userNotFound;
  static String get wrongPassword => _s.wrongPassword;
  static String get emailAlreadyExists => _s.emailAlreadyExists;
  static String get weakPassword => _s.weakPassword;
  static String get invalidOtpCode => _s.invalidOtpCode;
  static String get otpExpired => _s.otpExpired;
  static String get tooManyAttemptsTryLater => _s.tooManyAttemptsTryLater;
  static String get networkErrorShort => _s.networkErrorShort;
  static String get selectItem => _s.selectItem;
}
